# Properties cold calling list with score

## Project steps
1- Extracting the data from public county gis

2- Cleaning the data

In [6]:
import requests
import pandas as pd
import math
import numpy as np
from bs4 import BeautifulSoup
import os

In [7]:
BASE_URL = "https://gis.aacounty.org/arcgis/rest/services/OpenData/Structure_OpenData/MapServer/0/query"

BATCH_SIZE = 1000

offset = 0
csv_file = "MD_Anne_Arnuld_GDSC.csv"

while True:
    params = {
        "f": "json",
        "where": "1=1",
        "outFields": "*",
        "resultRecordCount": BATCH_SIZE,
        "resultOffset": offset,
        "orderByFields": "OBJECTID ASC"
    }

    response = requests.get(BASE_URL, params=params)
    data = response.json()


    features = data.get("features", [])

    if not features:
        print("No more data to fetch.")
        break
         
    df = pd.json_normalize([f["attributes"] for f in features])

    df.to_csv(
        csv_file,
        mode="a",
        index=False,
        header=not os.path.exists(csv_file),
        encoding="utf-8-sig"
    )
    print(f"Added {len(df)} records.")

    offset += BATCH_SIZE

print(f"All data saved to {csv_file}")

Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 1000 records.
Added 457 records.
No more data to fetch.
All data saved to MD_Anne_Arnuld_GDSC.csv

In [11]:
df = pd.read_csv("MD_Anne_Arnuld_GDSC.csv")

C:\Users\user\AppData\Local\Temp\ipykernel_14912\1359634754.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("MD_Anne_Arnuld_GDSC.csv")

,OBJECTID,ADDRPT_ID,MASTER_ID,PT_TYPE,FULL_ADDRE,ST_NUMBER,ST_NUMSUFF,ST_PREFIXD,ST_NAME,ST_TYPE,...,CAD_ADDR,COMMENTS,POINT_X,POINT_Y,STRUC_TYPE,GlobalID,created_us,created_da,last_edite,last_edi_1
0,1,6001687,0,ADDRESS,"625 IRVIN AVE, 20751",625,,,IRVIN,AVE,...,625 IRVIN AV,ADDED PT_TYPE,1439283.965,402495.2904,SFD,{2C227459-6D66-4968-9676-BB2BD456CF67},,1.224810e+12,GIS_AnneArundel,1.741820e+12
1,2,6001692,0,ADDRESS,"626 IRVIN AVE, 20751",626,,,IRVIN,AVE,...,626 IRVIN AV,,1439211.749,402767.2886,SFD,{1FF38C66-6BD9-4750-ABF7-B80327084922},,1.224810e+12,pzmagl22,1.740440e+12
2,3,6001700,0,ADDRESS,"615 IRVIN AVE, 20751",615,,,IRVIN,AVE,...,615 IRVIN AV,,1439111.054,402678.7467,SFD,{CA218AD6-6785-4FC1-9B24-CF3945C6DB13},,1.224810e+12,ITMAGL23,1.595810e+12

In [14]:
# to display all the columns without limit
pd.set_option('display.max_columns', None)
df.head(3)

,OBJECTID,ADDRPT_ID,MASTER_ID,PT_TYPE,FULL_ADDRE,ST_NUMBER,ST_NUMSUFF,ST_PREFIXD,ST_NAME,ST_TYPE,ST_SUFFIXD,BLDG_NAME,SOURCE,CITY_NAME,UNIT_TYPE,UNITNUM,FLOOR,UNIT_ADDR,SUB_ADDR,BUS_NAME,AA_POI,ZIPCODE,AAID,AA_CP,BMC_ID,ACCESS_X,ACCESS_Y,BLDG_CODE,BLDG_ID,RESTRICTED,CAD_ST_TYP,CAD_ADDR,COMMENTS,POINT_X,POINT_Y,STRUC_TYPE,GlobalID,created_us,created_da,last_edite,last_edi_1
0,1,6001687,0,ADDRESS,"625 IRVIN AVE, 20751",625,,,IRVIN,AVE,,,PHYSICALLY VERIFIED IN FIELD,DEALE,,,0,,,,N,20751,6371,N,1,0.0,0.0,RESIDENTIAL,,0,AV,625 IRVIN AV,ADDED PT_TYPE,1439283.965,402495.2904,SFD,{2C227459-6D66-4968-9676-BB2BD456CF67},,1.224810e+12,GIS_AnneArundel,1.741820e+12
1,2,6001692,0,ADDRESS,"626 IRVIN AVE, 20751",626,,,IRVIN,AVE,,,PHYSICALLY VERIFIED IN FIELD,DEALE,,,0,,,,N,20751,6371,N,1,0.0,0.0,RESIDENTIAL,,0,AV,626 IRVIN AV,,1439211.749,402767.2886,SFD,{1FF38C66-6BD9-4750-ABF7-B80327084922},,1.224810e+12,pzmagl22,1.740440e+12
2,3,6001700,0,ADDRESS,"615 IRVIN AVE, 20751",615,,,IRVIN,AVE,,,PHYSICALLY VERIFIED IN FIELD,DEALE,,,0,,,,N,20751,6371,N,1,0.0,0.0,RESIDENTIAL,,0,AV,615 IRVIN AV,,1439111.054,402678.7467,SFD,{CA218AD6-6785-4FC1-9B24-CF3945C6DB13},,1.224810e+12,ITMAGL23,1.595810e+12